implement sport detail page with api connection
SPaM-Skill-Issue/sota-frontend pull request #3
Opened 2023-11-06 15:12 UTC by Supakrit65

![fsdffdsdfs](https://github.com/SPaM-Skill-Issue/sota-frontend/assets/92836314/db77afca-dd6f-48af-940e-cbf9411c53a7)

- Connect to backend api
- Try replicating mockup layout

2023-11-07 09:21 UTC, Savetang19 requested changes

2023-11-07 09:21 UTC, Savetang19 commented on src/pages/sportDetail.tsx
> +        const nextPage = parseInt(id!, 10) - 1;
Please change const name from  `nextPage` to `previousPage`

2023-11-07 09:21 UTC, Savetang19 commented on src/pages/sportDetail.tsx
- Can you handle the error that for `any sport that doesn't exist`, change it to redirect to `sport ID 1`.
- For path `/sports/0` it shows `Archery` which its ID is `1`.

2023-11-07 09:55 UTC, GToidZ commented on src/pages/sportDetail.tsx
> +        if (Number(id) > 0 && id) { fetchSport(id); }
```suggestion
        if (id && parseInt(id, 10) > 0) { fetchSport(id); }
```

Please check for null before parsing integer.

2023-11-07 09:57 UTC, GToidZ requested changes
A little bit more change won't hurt 😀

2023-11-07 10:33 UTC, Savetang19 approved these changes
![image](https://github.com/SPaM-Skill-Issue/sota-frontend/assets/89629829/157cb729-364c-4a54-bc6b-0d8d5c46bd25)

LGTM!!! Nice ๆ

2023-11-08 02:21 UTC, RyukungG approved these changes
Good ๆ
![](https://media.tenor.com/CDsybQkGp_kAAAAC/thumbs-up-approve.gif)

2023-11-08 04:37 UTC, GToidZ approved these changes
LGTM

2023-11-08 07:08 UTC, merged